package Triangle.CodeGenerator.LLVM;

import Triangle.CodeGenerator.LLVM.LLVMGenerator.Request.OptimizationLevel;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Minimal integration with the local LLVM toolchain. This helper focuses on invoking {@code clang}
 * to turn the IR generated by {@link LLVMGenerator} into a native executable that can be launched
 * from the IDE. The implementation deliberately keeps the contract small so it is easy to replace
 * or extend later (for example to expose {@code llc} / {@code lld} separately, or to allow custom
 * arguments).
 */
public final class NativeToolchain {

  private NativeToolchain() {
  }

  public static final class Request {

    private final Path llvmIrPath;
    private final Path outputExecutable;
    private final OptimizationLevel optimizationLevel;
    private final List<String> additionalArgs;

    private Request(Builder builder) {
      this.llvmIrPath = builder.llvmIrPath;
      this.outputExecutable = builder.outputExecutable;
      this.optimizationLevel = builder.optimizationLevel;
      this.additionalArgs = new ArrayList<>(builder.additionalArgs);
    }

    public Path llvmIrPath() {
      return llvmIrPath;
    }

    public Path outputExecutable() {
      return outputExecutable;
    }

    public OptimizationLevel optimizationLevel() {
      return optimizationLevel;
    }

    public List<String> additionalArgs() {
      return additionalArgs;
    }

    public static Builder newBuilder(Path llvmIrPath, Path outputExecutable) {
      return new Builder(llvmIrPath, outputExecutable);
    }

    public static final class Builder {

      private final Path llvmIrPath;
      private final Path outputExecutable;
      private OptimizationLevel optimizationLevel = OptimizationLevel.NONE;
      private final List<String> additionalArgs = new ArrayList<>();

      private Builder(Path llvmIrPath, Path outputExecutable) {
        if (llvmIrPath == null) {
          throw new IllegalArgumentException("llvmIrPath");
        }
        if (outputExecutable == null) {
          throw new IllegalArgumentException("outputExecutable");
        }
        this.llvmIrPath = llvmIrPath.toAbsolutePath();
        this.outputExecutable = outputExecutable.toAbsolutePath();
      }

      public Builder setOptimizationLevel(OptimizationLevel level) {
        if (level != null) {
          this.optimizationLevel = level;
        }
        return this;
      }

      public Builder addArgument(String arg) {
        if (arg != null && !arg.isEmpty()) {
          additionalArgs.add(arg);
        }
        return this;
      }

      public Request build() {
        return new Request(this);
      }
    }
  }

  public static final class Result {

    private final int exitCode;
    private final List<String> command;

    private Result(int exitCode, List<String> command) {
      this.exitCode = exitCode;
      this.command = command;
    }

    public int exitCode() {
      return exitCode;
    }

    public List<String> command() {
      return command;
    }

    public boolean isSuccess() {
      return exitCode == 0;
    }
  }

  public static Result compileToNative(Request request) throws IOException, InterruptedException {
    if (request == null) {
      throw new IllegalArgumentException("request");
    }
    Path irPath = request.llvmIrPath();
    if (!Files.isRegularFile(irPath)) {
      throw new IOException("LLVM IR file does not exist: " + irPath);
    }
    Path outputPath = request.outputExecutable();
    File parent = outputPath.getParent().toFile();
    if (parent != null && !parent.exists() && !parent.mkdirs()) {
      throw new IOException("Unable to create directory: " + parent);
    }

    List<String> command = new ArrayList<>();
    command.add(resolveClangExecutable());
    command.add(irPath.toString());
    command.add("-o");
    command.add(outputPath.toString());

    String optFlag = optimizationFlag(request.optimizationLevel());
    if (!optFlag.isEmpty()) {
      command.add(optFlag);
    }
    command.addAll(request.additionalArgs());

    ProcessBuilder builder = new ProcessBuilder(command);
    builder.redirectErrorStream(true);
    Process process = builder.start();
    try (BufferedReader reader = new BufferedReader(
        new InputStreamReader(process.getInputStream()))) {
      String line;
      while ((line = reader.readLine()) != null) {
        System.out.println(line);
      }
    }
    int exit = process.waitFor();
    return new Result(exit, command);
  }

  /**
   * Compile the given LLVM IR file to native assembly using clang (-S).
   */
  public static Result compileToAssembly(Request request) throws IOException, InterruptedException {
    if (request == null) {
      throw new IllegalArgumentException("request");
    }
    Path irPath = request.llvmIrPath();
    if (!Files.isRegularFile(irPath)) {
      throw new IOException("LLVM IR file does not exist: " + irPath);
    }
    Path outputPath = request.outputExecutable();
    File parent = outputPath.getParent().toFile();
    if (parent != null && !parent.exists() && !parent.mkdirs()) {
      throw new IOException("Unable to create directory: " + parent);
    }

    List<String> command = new ArrayList<>();
    command.add(resolveClangExecutable());
    command.add("-S");
    String optFlag = optimizationFlag(request.optimizationLevel());
    if (!optFlag.isEmpty()) {
      command.add(optFlag);
    }
    command.add(irPath.toString());
    command.add("-o");
    command.add(outputPath.toString());
    command.addAll(request.additionalArgs());

    ProcessBuilder builder = new ProcessBuilder(command);
    builder.redirectErrorStream(true);
    Process process = builder.start();
    try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
      String line;
      while ((line = reader.readLine()) != null) {
        System.out.println(line);
      }
    }
    int exit = process.waitFor();
    return new Result(exit, command);
  }

  /**
   * Compile the given LLVM IR file to an object file using clang (-c).
   */
  public static Result compileToObject(Request request) throws IOException, InterruptedException {
    if (request == null) {
      throw new IllegalArgumentException("request");
    }
    Path irPath = request.llvmIrPath();
    if (!Files.isRegularFile(irPath)) {
      throw new IOException("LLVM IR file does not exist: " + irPath);
    }
    Path outputPath = request.outputExecutable();
    File parent = outputPath.getParent().toFile();
    if (parent != null && !parent.exists() && !parent.mkdirs()) {
      throw new IOException("Unable to create directory: " + parent);
    }

    List<String> command = new ArrayList<>();
    command.add(resolveClangExecutable());
    String optFlag = optimizationFlag(request.optimizationLevel());
    if (!optFlag.isEmpty()) {
      command.add(optFlag);
    }
    command.add("-c");
    command.add(irPath.toString());
    command.add("-o");
    command.add(outputPath.toString());
    command.addAll(request.additionalArgs());

    ProcessBuilder builder = new ProcessBuilder(command);
    builder.redirectErrorStream(true);
    Process process = builder.start();
    try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
      String line;
      while ((line = reader.readLine()) != null) {
        System.out.println(line);
      }
    }
    int exit = process.waitFor();
    return new Result(exit, command);
  }

  private static String resolveClangExecutable() {
    String explicit = System.getenv("CLANG_PATH");
    if (explicit != null && !explicit.isEmpty()) {
      return explicit;
    }
    String llvmHome = System.getenv("LLVM_HOME");
    if (llvmHome != null && !llvmHome.isEmpty()) {
      Path candidate = Paths.get(llvmHome, "bin", defaultExecutableName());
      if (Files.isRegularFile(candidate)) {
        return candidate.toString();
      }
    }
    return defaultExecutableName();
  }

  private static String defaultExecutableName() {
    return isWindows() ? "clang.exe" : "clang";
  }

  private static boolean isWindows() {
    String os = System.getProperty("os.name", "");
    return os.toLowerCase(Locale.ROOT).contains("win");
  }

  private static String optimizationFlag(OptimizationLevel level) {
    if (level == null) {
      return "";
    }
    switch (level) {
      case NONE:
        return "-O0"; // Explicitly disable optimizations
      case O1:
        return "-O1"; // Some lightweight optimizations
      case O2:
        return "-O2"; // Balanced optimization level
      case O3:
        return "-O3"; // Aggressive optimizations
      default:
        return "";
    }
  }
}
